### ISSUE TITLE
can´t find devices

### ISSUE THREAD

**Issue by Dane809** [razorRun/node-red-contrib-smartlifeair#5] opened 2020-06-20 18:11 UTC
Tried different account locations but can´t find my devices.
Nice idea but don´t work.
Can´t flash my devices with tasmota so i decided to try this node but without success.

**Comment by razorRun** [comment] 2020-06-20 20:08
Hey

Did  you register the account using smart life air app ( not smart life) ,
select the country as NZ.

Can you operate devices directly from the app?

If that’s the case when you register on the middle ware, can you see your
device on the message?

**Comment by Dane809** [comment] 2020-06-20 20:49
Hey, I  registered the devices and can control them from the smartlife air app (location:nz). The device is not visible on the smartlife homepage

**Comment by zraken** [comment] 2020-06-26 19:24
I'm having similar issues. I created the accounts and able to control a switch with the smart life air app as well as see the device from the middle ware. When I try to set up device on node red it says "Loading" under "Select Device" and it never shows the device. See screenshot.
![screenshot](https://user-images.githubusercontent.com/59450270/85893565-165d3600-b7c1-11ea-8035-08e6f46977de.png)

**Comment by razorRun** [comment] 2020-07-15 23:36
duplicate of this[ issue ](https://github.com/razorRun/node-red-contrib-smartlifeair/issues/2)

**Closed by razorRun** 2020-07-15 23:36 UTC
